version: '3.9'

services:
  db:
    container_name: umigame-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: umigame-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
  
  app:
    container_name: umigame-api
    depends_on:
      - db
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"

volumes:
  umigame-db-volume: