version: '3.9'

services:
  db:
    container_name: umigame-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_ROOTUSER", "-p$MYSQL_ROOTPASS"]
      interval: 3s
      retries: 2
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: umigame-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
  
  app:
    container_name: umigame-api
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "10081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "10082:8080"
    volumes:
      - type: bind
        source: ./api_reference.yaml
        target: /usr/share/nginx/html/api_reference.yaml
    environment:
      API_URL: api_reference.yaml
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "10083:4010"
    command: mock -h 0.0.0.0 /api_reference.yaml
    volumes:
      - type: bind
        source: ./api_reference.yaml
        target: /api_reference.yaml

volumes:
  umigame-db-volume: