info:
  contact: {}
paths:
  /problem/list:
    get:
      consumes:
      - application/json
      description: 問題リストの取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      security:
      - UUID: []
      summary: 問題リストの取得
swagger: "2.0"
